# Generated by Django 3.1.7 on 2021-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
